### PR TITLE
Fix Phake errors + other build errors

### PR DESCRIPTION
**Pull request by WyriHaximus**
Work in Progress please don't merge yet, opened it so you can follow my progress :smile: .

### CODE REVIEW

**Comment by ADmad** [comment]
LOL, you made a PR to my fork for PR to your repo :laughing:

**Comment by WyriHaximus** [comment]
That's how I roll 😎

**Comment by ADmad** [comment]
Builds are failing with error `parallel-lint: not found`

**Comment by WyriHaximus** [comment]
Build seems mostly fixed now, maybe a kick to the 17.6 will make it fully green.

**Comment by WyriHaximus** [comment]
> Cool, though you can just push additional changes on top of my PR branch.

Could have done that, but once in a while I like to do it this way because of your initial reaction :sunglasses:

**Comment by ADmad** [comment]
Instead of `nightly` (which is now PHP 7.4-dev) it would be better to use 7.3.0RC1. That requires using `xenial` and installing a lib. You can check travis config of cakephp repo.

**Comment by ADmad** [comment]
> Could have done that, but once in a while I like to do it this way because of your initial reaction

Hehe, okay. I have merged this so you can now directly push commits to my branch if required or merge my PR :slightly_smiling_face:

**Comment by WyriHaximus** [comment]
> Instead of `nightly` (which is now PHP 7.4-dev) it would be better to use 7.3.0RC1. That requires using `xenial` distro and installing a lib. You can check travis config of cakephp repo.

Done the same on one of my repo's over the weekend, slightly different so only the `7.3` jobs use `xenial`: https://github.com/WyriHaximus/recoilphp-callable/blob/master/.travis.yml#L17-L34

**Comment by WyriHaximus** [comment]
> > Could have done that, but once in a while I like to do it this way because of your initial reaction
> 
> Hehe, okay. I have merged this so you can now directly push commits to my branch if required or merge my PR

Will do :+1:

**Comment by ADmad** [comment]
> Done the same on one of my repo's over the weekend, slightly different

Ah yes, I learnt about how to switch distro only for a particular job after I had already got the changes ready for cakephp repo and then didn't bother to update later.

**Pull request merged**
